name 'example42-sudo'
version '2.0.10'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-sudo'
summary 'Puppet module for sudo'
description 'This module installs and manages sudo'
dependency 'example42/puppi', '>=2.0.0'
dependency 'ripienaar/concat', '>=0.0.1'
