name    'lab42-sudo'
version '2.0.7'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-sudo'
summary 'Puppet module for sudo'
description 'This module installs and manages sudo'
dependency 'lab42/puppi', '>= 2.0.0'
